import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "~/_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "~/components/ui/sonner";
import { CSPostHogProvider } from "./_analytics/provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
export const metadata = {
  title: "Create T3 Gallery",
  description: "Generated by greecetop",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const messages = await getMessages();

  return (
    <ClerkProvider>
      <CSPostHogProvider>
        <html lang="en">
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <NextIntlClientProvider messages={messages}>
            <body className={`dark flex flex-col gap-4`}>
              <div className=" grid-rows-[auto,1fr]">
                <TopNav />
                <main className="overflow-y-auto"> {children} </main>
              </div>
              {modal}
              <div id="modal-root" />
              <Toaster />
            </body>
          </NextIntlClientProvider>
        </html>
      </CSPostHogProvider>
    </ClerkProvider>
  );
}
